version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket codepipeline-us-east-1-752693302569 --output-template-file output-template.yml --debug
artifacts:
  files:
    - template.yml
    - output-template.yml